# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dn2yIqO5LEvZhwJTOPGCXXQKanv6Zlfs
"""

def prefix_suffix(s):
    n = len(s)
    if n <= 1: # иначе proper
        return ""

    pi = [0] * n

    for i in range(1, n):
        j = pi[i - 1]
        while j > 0 and s[i] != s[j]:
            j = pi[j - 1]
        if s[i] == s[j]:
            j += 1
        pi[i] = j
    result_length = pi[n - 1]

    return s[:result_length] if result_length > 0 else ""

test = "abaaabscabaa"
result = prefix_suffix(test)
print(f"'{test}' result '{result}'")